### ISSUE TITLE
SSO Authentication issue: unable to access profile page.

### ISSUE THREAD

**Issue by geoangelotti** [kirinnee/oreilly-downloader#2]
Hello @kirinnee,

When trying to download a book with sso authentication I get this issue.

It is related to lorenzodifuccia/safaribooks#273.

https://github.com/lorenzodifuccia/safaribooks/commit/c872f22f29e2432af5a9372272a5535e64790d2c fixes it.

You just need to rebuild the docker image to fix it.

**Comment by kirinnee** [comment]
Should be fixed, I would appreciate it if you can verify it! @geoangelotti

**Comment by geoangelotti** [comment]
It works!
Thanks :)
