### ISSUE TITLE
cat: '' no such file or directory

### ISSUE THREAD

**Issue by engineeringsys** [kirinnee/oreilly-downloader#3]
When using the sso or standard login per the repo instructions when the docker container pulls and builds I receive:

`[#] Unhandled Exception: Expecting value: line 1 column 1 (char 0) (type: JSONDecodeError)
[!] Aborting...                                                                 
cat: '': No such file or directory
Please * the Docker wrapper on GitHub t`

**Comment by kirinnee** [comment]
please show the command you have used thank you!

**Comment by rushic24** [comment]
https://github.com/lorenzodifuccia/safaribooks/pull/317 This worked for me
