### ISSUE TITLE
Download contains only preface and table of content

### ISSUE THREAD

**Issue by dannyyy** [kirinnee/oreilly-downloader#6]
Hi,
I tried to download the book "Rx.NET in Action" with id 9781617293061.
The downloaded .epub file contains only the cover, preface and table of content. But the download is quite large (~10MB) for just 38 text pages.
I tried to open the ebook on several applications (android, macos, windows) as well as on my Kobo ebook reader.

Could you confirm, that you get the same result? Just to exclude any hidden authentication issues.

**Comment by Acovid** [comment]
I get a normal book. With all content, properly formatted etc... File size is 10.9 MB.

**Comment by dannyyy** [comment]
In the mean time I found out that my subscription has expired. Interestingly, on a desktop browser were the books still available.

After renewing everything works fine. Thank you for checking it ou.
